### ISSUE TITLE
Usage of .get() without args?

### ISSUE THREAD

**Issue by PeteHaitch** [tatami-inc/beachmat#4]
Hey Aaron,

The **beachmat** vignette says:

- `dptr->get(r, c)` returns a double at matrix entry `(r, c)`.

What is it returning when no arguments are supplied? E.g. as in the below line taken from https://github.com/davismcc/scater/blob/63fe22b32b1fc78541a876f3b11cf1973bdeadd5/src/calc_exprs.cpp#L125

```Cpp
return calc_exprs_internal<int, Rcpp::IntegerVector>(mat.get(), size_fac, sf_use, prior_count, log, sum, subset);
```

Thanks,
Pete

**Comment by LTLA** [comment]
Ah, that's a different `get`. Recall that `dptr` is a `unique_ptr<numeric_matrix>`. Calling

```r
dptr->get(r, c)
```

will return a  `double` as promised. However, calling

```r
dptr.get()
```

will return the raw `numeric_matrix` pointer. This is useful because unique pointers cannot be passed by copy, requiring us to instead pass a raw pointer to internal functions.

In short, `->` calls the `get` method of the `numeric_matrix` itself (i.e., it does `(*dptr).get(r, c)`), whereas `.` calls the method for the `unique_ptr` pointing to the `numeric_matrix`.

**Comment by PeteHaitch** [comment]
Ahh ok, I think I get that. Thanks for the explanation. I'm still fumbling around in the dark a bit with this stuff.
